server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://XXXX:3306/ian_db?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: XXXX
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.hraps.ianserver.entity
